- name: Enable Sybase server port in Firewalld
  firewalld:
    port: "{{ sybase.networking.port }}/tcp"
    permanent: true
    state: enabled
    zone: public
  notify: Restart firewalld
  #when: firewall.enabled

- name: Enable Sybase backup server port in Firewalld
  firewalld:
    port: "{{ sybase.networking.backup_port }}/tcp"
    permanent: true
    state: enabled
    zone: public
  notify: Reload firewall rules
  #when: firewall.enabled