- name: ASE | OS preparation
  import_tasks: osprep.yaml

- name: ASE | Configure
  import_tasks: config.yaml

- name: ASE | Install
  import_tasks: install.yaml

- name: ASE | Firewall
  import_tasks: firewall.yaml