# User to run SAP ASE 
sybase:
  version: 16.0.2.2
  user: 'sybase'
  group: 'sybase'
  # Password the SAP ASE internal 'sa' account
  sa_password: 'myPassword'
  install:
    client:
      # Kernel Share Memory
      kernel_shmmax: 2147483648
      # SAP ASE Download url 
      archive_url: 'http://repository.transtep.com/repository/thirdparty/sybase/ASE16SP02/ASE_Suite.linuxamd64.tgz'
      # Vagrant Only
      archive_vagrant: /vagrant/hack/vagrant/packages/ASE_Suite.linuxamd64.tgz
      archive_checksum: 'sha256:e975d282fdab520e6b690df7ec5aa14c3aacf91adc6171687856a7d12d1b3d4c'
      # Sybase installation directory
      directory: '/home/sybase'
      # Run silent installation
      silent: 'True'
      # Installed features:
      features: 'fopen_client,fdblib,fjconnect70,fsysam_util,fscc_server,fasemap,fase_snmp_agent'
  networking:
    # Sybase listen ports
    interface: 'database.local'
    port: '5000'
    backup_port: '5001'
    # Name of the database server to add in the ${SYBASE}/interfaces 
    name: 'MYSYBASE'