#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html

# Create Groups
groups:
  - sybase

# Create Users
users:
  - name: sybase
    geos: SAP Adaptive Server Enterprise user
    primary_group: sybase
    groups: root
    sudo: ALL=(ALL) ALL

# Set the locale
locale: en_US.UTF-8

# Set the timezone for this instance
timezone: UTC

# Do not recreate server ssh keys
ssh_deletekeys: False

# Additional packages to be installed
package_update: True
packages:
  - htop
  - curl
  # Sybase : https://help.sap.com/viewer/23c3bb4a29be443ea887fa10871a30f8/16.0.2.9/en-US/6302c568328c4f599bd0209e6beb1e4c.html
  - compat-libstdc++-33-3.2.3-72.el7.x86_64
  - libaio
  - glibc
  - compat-glibc-2.5-46.2.x86_64
  - glibc.i686
  - libXtst-devel
  - libXi-devel
  - openmotif-devel
  - libXmu-devel
  - libXt-devel
  - libXext-devel
  - libXp-devel
  - libX11-devel
  - libSM-devel
  - libICE-devel
  # Python 3
  - python3
  - python3-devel
  - python3-pip
  - python3-setuptools
  - libselinux-python3
  # Python 2
  - python
  - python-devel
  - python-pip
  - python-setuptools
  - libselinux-python
runcmd:
  # Install Ansible
  - ['/usr/bin/pip3', 'install', 'ansible==2.9']