---
bastion:
  hosts:
    bastion.vagrant:
      ansible_host: 127.0.0.1
      ansible_port: 42222
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: hack/vagrant/.vagrant/machines/bastion/virtualbox/private_key

database:
  hosts:
    database.vagrant:
      ansible_host: 127.0.0.1
      ansible_port: 52222
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: hack/vagrant/.vagrant/machines/database/virtualbox/private_key