- name: Create Liquidbase directory
  file:
    name: "{{ liquidbase.install.directory }}"
    state: directory
    mode: 0750

- name: Download and install Liquidbase
  unarchive:
    src: "https://github.com/liquibase/liquibase/releases/download/v{{ liquidbase.version }}/liquibase-{{ liquidbase.version }}.tar.gz"
    des: "{{ liquidbase.install.directory }}"
