---
galaxy_info:
  author: Florian JUDITH
  description: AdoptOpenJDK 8 JDK
  license: limited
  min_ansible_version: 2.8
  platforms:
    - name: CentOS
      versions:
      - 7
    - name: EL
      versions:
      - 7
  galaxy_tags:
    - java
    - java8
    - jdk
    - jdk8
    - adoptopenjdk

dependencies: []