- name: Check if Sybase already installed
  stat:
    path: "{{ sybase.install.server.directory }}/SYBASE.sh"
  register: sybase_install

- name: Check if Server already built
  stat:
    path: "{{ sybase.install.server.directory }}/ASE_16.0/install/SYBASE.sh/RUN_{{ sybase.networking.name }}"
  register: sybase_build

- name: Install Sybase
  # become: true
  # become_user: "{{ sybase.user }}"
  command: |
    /tmp/ASE_Suite/setup.bin -f /tmp/sybase-ase-response.conf \
    -i silent \
    -DAGREE_TO_SAP_LICENSE=true \
    -DRUN_SILENT=true \
  when: not sybase_install.stat.exists

- name: Build Sybase server
  # become: true
  # become_user: "{{ sybase.user }}"
  shell: |
    source {{ sybase.install.server.directory }}/SYBASE.sh && \
    {{ sybase.install.server.directory }}/ASE-16_0/bin/srvbuildres -r /tmp/sybase-ase.rs
  when: not sybase_build.stat.exists

- name: Configure Sybase interfaces
  template:
    src: interfaces.j2
    dest: "{{ sybase.install.server.directory }}/interfaces"
    owner: "{{ sybase.user }}"
    group: "{{ sybase.group }}"
    mode: 0440

- name: Copy Sybase startup script
  template:
    src: start-server.sh.j2
    dest: "{{ sybase.install.server.directory }}/bin/start-server.sh"
    owner: "{{ sybase.user }}"
    group: "{{ sybase.group }}"
    mode: 0750

- name: Copy Sybase stop script
  template:
    src: stop-server.sh.j2
    dest: "{{ sybase.install.server.directory }}/bin/stop-server.sh"
    owner: "{{ sybase.user }}"
    group: "{{ sybase.group }}"
    mode: 0750

- name: Install Sybase Systemd service
  template:
    src: sybase.service.j2
    dest: /etc/systemd/system/sybase.service
    mode: 0755
    owner: root
    group: root

- name: Enable Sybase Systemd service
  systemd:
    name: sybase.service
    enabled: yes
    masked: no
    state: started

- name: Create SA password file
  copy:
    dest: "{{ sybase.install.server.directory }}/.sa_password"
    content: |
      {{ sybase.sa_password }}
    owner: "{{ sybase.user }}"
    group: "{{ sybase.group }}"
    mode: 0400

- name: Update .bashrc
  become: true
  become_user: "{{ sybase.user }}"
  lineinfile:
    path: "{{ sybase.install.server.directory }}/.bashrc"
    line: "source {{ sybase.install.server.directory }}/SYBASE.sh"