#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html

# Create Groups
groups:
  - sybase

# Create Users
users:
  - name: sybase
    geos: SAP Adaptive Server Enterprise user
    primary_group: sybase
    groups: root

# Set the locale
locale: en_US.UTF-8

# Set the timezone for this instance
timezone: UTC

# Do not recreate server ssh keys
ssh_deletekeys: False

# Additional packages to be installed
package_update: True
packages:
  - nano
  - vim
  - wget
  - gtk2
  - libaio
  - glibc
  - glibc.686